version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ~/db/mysql:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      TERM: xterm
      APP_ENV: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: abc@123
      MYSQL_DATABASE: picoworker
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8888:80
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8889:8081"
    depends_on:
        - redis
volumes:
  dbdata: