version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ~/db/mysql:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      TERM: xterm
      APP_ENV: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: abc@123
      MYSQL_DATABASE: picoworker
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8888:80

volumes:
  dbdata: